name: DeployToGitHubPages
env:
  PUBLISH_DIR: callum-imrie.github.io/bin/Release/net5.0/publish/wwwroot

# Controls when the action will run
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish app
        run: dotnet publish -c Release

      # changes the base-tag in index.html from '/' to 'callum-imrie.github.io' to match GitHub Pages repository subdirectory
      - name: Change base-tag in index.html from / to callum-imrie.github.io
        run: sed -i 's/<base href="\/" \/>/<base href="\/callum-imrie.github.io\/" \/>/g' release/wwwroot/index.html

      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.5.1
        with:
          target_branch: gh-pages
          build_dir: ${{ env.PUBLISH_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}